import { Property, PropertyType, FurnishingStatus, AmenityType } from './types';

export const PROPERTIES_DATA: Property[] = [
  {
    id: 'prop-1',
    title: 'Elite Boys PG with Meals near LPU',
    price: 4500,
    type: 'PG',
    location: 'Law Gate, Near LPU',
    address: 'Street No. 3, Law Gate Area, Maheru, Phagwara, Punjab 144411',
    bedrooms: 1,
    bathrooms: 1,
    furnishing: 'Furnished',
    ac: true,
    nearLPU: true,
    distanceToLPU: '150m (2 mins walk to Law Gate)',
    images: [
      'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1598928506311-c55ded91a20c?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=800&q=80'
    ],
    securityDeposit: 3000,
    brokerage: 0,
    description: 'Perfect, modern and secure PG environment tailored specially for LPU students. Features highly hygienic triple meal plan, high-speed WiFi, modern study desk, cozy orthopedic beds, and separate wardrobe facilities. Daily housekeeping is included in the rent. Pure drinking RO water is available on each floor.',
    rating: 4.8,
    reviewsCount: 34,
    amenities: ['WiFi', 'Bed', 'AC', 'Kitchen', 'RO Water', 'Study Table', 'CCTV', 'Power Backup', 'Meals Included', 'Refrigerator'],
    size: '180 sq.ft',
    genderPreference: 'Boys',
    hostName: 'Sardar Manpreet Singh',
    hostPhone: '+91 98765 43210',
    hostWhatsApp: '919876543210',
    hostAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
    featured: true,
    addedDate: '2026-06-15'
  },
  {
    id: 'prop-2',
    title: 'Premium Girls PG (Stanza Living Style)',
    price: 6500,
    type: 'PG',
    location: 'Maheru, Near LPU',
    address: 'Elite Enclave, Maheru Road, near Lovely Professional University, Phagwara, Punjab 144411',
    bedrooms: 1,
    bathrooms: 1,
    furnishing: 'Furnished',
    ac: true,
    nearLPU: true,
    distanceToLPU: '600m (6 mins walk)',
    images: [
      'https://images.unsplash.com/photo-1598928506311-c55ded91a20c?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?auto=format&fit=crop&w=800&q=80'
    ],
    securityDeposit: 5000,
    brokerage: 0,
    description: 'Premium luxury accommodation for female students and professionals. Multi-tier biometric security, strictly supervised access, fully chef-crafted vegetarian food (breakfast, lunch, evening snacks & dinner). Highly spacious double-sharing layout with individual AC, study units, high-end laundry systems, and dedicated high-speed fiber internet.',
    rating: 4.7,
    reviewsCount: 42,
    amenities: ['WiFi', 'Bed', 'AC', 'Kitchen', 'Washing Machine', 'RO Water', 'Study Table', 'CCTV', 'Power Backup', 'Meals Included', 'Geyser', 'Refrigerator'],
    size: '220 sq.ft',
    genderPreference: 'Girls',
    hostName: 'Mrs. Rajinder Kaur',
    hostPhone: '+91 98123 45678',
    hostWhatsApp: '919812345678',
    hostAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=150&q=80',
    featured: true,
    addedDate: '2026-06-18'
  },
  {
    id: 'prop-3',
    title: 'Modern 1 BHK Luxury Studio Apartment',
    price: 7500,
    type: '1 BHK',
    location: 'Urban Estate, Phagwara',
    address: 'Block-D, Urban Estate, Plahi Road, Phagwara, Punjab 144401',
    bedrooms: 1,
    bathrooms: 1,
    furnishing: 'Furnished',
    ac: true,
    nearLPU: false,
    distanceToLPU: '6.5 km',
    images: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&w=800&q=80'
    ],
    securityDeposit: 7500,
    brokerage: 1000,
    description: 'Fully high-end 1 BHK flat situated within the upscale, peaceful Urban Estate. Comes equipped with luxury fittings, separate drawing room, Modular kitchen with chimney, LED TV with cable connection, state of the art wooden wardrobe, and beautiful balcony facing the community green park.',
    rating: 4.9,
    reviewsCount: 18,
    amenities: ['WiFi', 'Bed', 'AC', 'Parking', 'Kitchen', 'Washing Machine', 'RO Water', 'Study Table', 'CCTV', 'Geyser', 'Power Backup', 'Refrigerator'],
    size: '550 sq.ft',
    genderPreference: 'Any',
    hostName: 'Raman Sharma',
    hostPhone: '+91 94676 12345',
    hostWhatsApp: '919467612345',
    hostAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80',
    featured: true,
    addedDate: '2026-06-10'
  },
  {
    id: 'prop-4',
    title: 'Fully Furnished 2 BHK House (First Floor)',
    price: 11000,
    type: '2 BHK',
    location: 'Hargobind Nagar, Phagwara',
    address: 'Street No. 12, Hargobind Nagar, adjacent Centra Mall Road, Phagwara, Punjab 144401',
    bedrooms: 2,
    bathrooms: 2,
    furnishing: 'Furnished',
    ac: true,
    nearLPU: false,
    distanceToLPU: '5.8 km',
    images: [
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=800&q=80'
    ],
    securityDeposit: 11000,
    brokerage: 0,
    description: 'Beautiful, newly painted 2 BHK flat on the first floor. Located in a pristine, elite residential area of Hargobind Nagar with premium markets within walking distance. Features two king-sized bedrooms, individual attached washrooms, large wardrobes, modular semi-furnished kitchen with chimney, and 24-hour car parking space.',
    rating: 4.6,
    reviewsCount: 15,
    amenities: ['WiFi', 'Bed', 'AC', 'Parking', 'Kitchen', 'RO Water', 'CCTV', 'Geyser', 'Power Backup', 'Refrigerator'],
    size: '1100 sq.ft',
    genderPreference: 'Family',
    hostName: 'Er. Gurdev Singh',
    hostPhone: '+91 98888 11223',
    hostWhatsApp: '919888811223',
    hostAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=150&q=80',
    featured: true,
    addedDate: '2026-06-05'
  },
  {
    id: 'prop-5',
    title: '3 BHK Independent House near Plahi Road',
    price: 14500,
    type: '3 BHK',
    location: 'Plahi Road, Phagwara',
    address: 'Near PLaza Palace, Plahi Bypass Road, Phagwara, Punjab 144401',
    bedrooms: 3,
    bathrooms: 3,
    furnishing: 'Semi Furnished',
    ac: false,
    nearLPU: false,
    distanceToLPU: '7.2 km',
    images: [
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80'
    ],
    securityDeposit: 15000,
    brokerage: 2000,
    description: 'Spacious independent 3 BHK building in a gated, secure compound. Massive front lawn, car garage, modular kitchen fixtures, clean bathrooms, and highly ventilated rooms. Ideal for medium-sized families or working professionals desiring space, safety, and excellent connectivity to Plahi Road market.',
    rating: 4.5,
    reviewsCount: 9,
    amenities: ['Bed', 'Parking', 'Kitchen', 'CCTV', 'Geyser', 'Power Backup'],
    size: '1800 sq.ft',
    genderPreference: 'Family',
    hostName: 'Dr. Ramesh Adhikari',
    hostPhone: '+91 94112 36729',
    hostWhatsApp: '919411236729',
    hostAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
    featured: false,
    addedDate: '2026-06-17'
  },
  {
    id: 'prop-6',
    title: 'Budget-Friendly Clean Room near Law Gate',
    price: 3200,
    type: 'Single Room',
    location: 'Law Gate, Near LPU',
    address: 'Kartar Lane, Maheru Road, Law Gate, Phagwara, Punjab 144411',
    bedrooms: 1,
    bathrooms: 1,
    furnishing: 'Semi Furnished',
    ac: false,
    nearLPU: true,
    distanceToLPU: '350m (4 mins walk)',
    images: [
      'https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?auto=format&fit=crop&w=800&q=80'
    ],
    securityDeposit: 2000,
    brokerage: 0,
    description: 'Affordable and highly peaceful independent single room with attached modern washroom. Best for self-sufficient students who prefer absolute privacy and quiet study environments. Shared washing machine access on the terrace. RO drinking water on tap, and reliable high-speed fiber WiFi.',
    rating: 4.4,
    reviewsCount: 19,
    amenities: ['WiFi', 'Bed', 'RO Water', 'Study Table', 'CCTV', 'Geyser'],
    size: '120 sq.ft',
    genderPreference: 'Any',
    hostName: 'Vikas Kumar',
    hostPhone: '+91 88998 77665',
    hostWhatsApp: '918899877665',
    hostAvatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=150&q=80',
    featured: false,
    addedDate: '2026-06-19'
  },
  {
    id: 'prop-7',
    title: 'Luxury 4 BHK Independent House (Villa Style)',
    price: 25000,
    type: '4 BHK',
    location: 'Urban Estate, Phagwara',
    address: 'H-67, Elite Block, Urban Estate Phase-2, Plahi Road, Phagwara, Punjab 144401',
    bedrooms: 4,
    bathrooms: 4,
    furnishing: 'Furnished',
    ac: true,
    nearLPU: false,
    distanceToLPU: '6.8 km',
    images: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=800&q=80'
    ],
    securityDeposit: 30000,
    brokerage: 5000,
    description: 'Presenting a spectacular, fully air-conditioned double-story 4 BHK Villa in Phagwara\'s finest luxury enclave. Features Italian marble flooring, premium False ceilings, a full modular designer kitchen with automated water purifiers, double-door refrigerator, automatic washing machine, expansive terrace, private driveway, and round-the-clock security surveillance.',
    rating: 4.9,
    reviewsCount: 11,
    amenities: ['WiFi', 'Bed', 'AC', 'Parking', 'Kitchen', 'Washing Machine', 'RO Water', 'Study Table', 'CCTV', 'Geyser', 'Power Backup', 'Refrigerator'],
    size: '2800 sq.ft',
    genderPreference: 'Family',
    hostName: 'Colonel Jasbir Singh Grewal',
    hostPhone: '+91 99119 22334',
    hostWhatsApp: '919911922334',
    hostAvatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=150&q=80',
    featured: true,
    addedDate: '2026-06-14'
  },
  {
    id: 'prop-8',
    title: 'Comfortable Sharing Room with AC near LPU (Girls)',
    price: 4000,
    type: 'Single Room',
    location: 'Maheru, Near LPU',
    address: 'Main Maheru Bazaar Road, Near LPU Front Gate, Phagwara, Punjab 144411',
    bedrooms: 1,
    bathrooms: 1,
    furnishing: 'Furnished',
    ac: true,
    nearLPU: true,
    distanceToLPU: '450m (5 mins walk)',
    images: [
      'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1560185007-c5ca9d2c014d?auto=format&fit=crop&w=800&q=80'
    ],
    securityDeposit: 3000,
    brokerage: 0,
    description: 'Extremely charming, safe, and air-conditioned room suitable for twin girls sharing. Located directly above a grocery sector so all daily requirements are accessible. Security is strictly monitored by CCTV 24 hours. Rental price includes daily water supply, high-speed WiFi, and routine garbage clearances.',
    rating: 4.5,
    reviewsCount: 22,
    amenities: ['WiFi', 'Bed', 'AC', 'RO Water', 'Study Table', 'CCTV', 'Geyser', 'Power Backup', 'Refrigerator'],
    size: '150 sq.ft',
    genderPreference: 'Girls',
    hostName: 'Asha Rani Saxena',
    hostPhone: '+91 97799 12345',
    hostWhatsApp: '919779912345',
    hostAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=150&q=80',
    featured: false,
    addedDate: '2026-06-08'
  },
  {
    id: 'prop-9',
    title: 'Modern Cozy PG Near Law Gate (Boys Only)',
    price: 3600,
    type: 'PG',
    location: 'Law Gate, Near LPU',
    address: 'Lane 2, Behind LPU Law Gate, Maheru, Phagwara, Punjab 144411',
    bedrooms: 1,
    bathrooms: 1,
    furnishing: 'Furnished',
    ac: false,
    nearLPU: true,
    distanceToLPU: '200m (2 mins walk)',
    images: [
      'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&w=800&q=80'
    ],
    securityDeposit: 2500,
    brokerage: 0,
    description: 'Clean, newly designed dual-sharing PG layout with modern study set-ups. High ventilated big windows, high-speed uninterrupted WiFi, RO water, power backup, CCTV security, and cooperative landlord. Mess facility option can be custom appended on nominal extra charge.',
    rating: 4.6,
    reviewsCount: 29,
    amenities: ['WiFi', 'Bed', 'RO Water', 'Study Table', 'CCTV', 'Power Backup'],
    size: '140 sq.ft',
    genderPreference: 'Boys',
    hostName: 'Deepak Thapar',
    hostPhone: '+91 95432 10987',
    hostWhatsApp: '919543210987',
    hostAvatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=150&q=80',
    featured: false,
    addedDate: '2026-06-12'
  },
  {
    id: 'prop-10',
    title: 'Peaceful 2 BHK Apartment on GT Road',
    price: 9000,
    type: '2 BHK',
    location: 'GT Road, Phagwara',
    address: 'Imperial Heights, GT Road Highway Sector, Phagwara, Punjab 144401',
    bedrooms: 2,
    bathrooms: 2,
    furnishing: 'Semi Furnished',
    ac: true,
    nearLPU: true,
    distanceToLPU: '4.2 km (10 mins via auto)',
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=80'
    ],
    securityDeposit: 9000,
    brokerage: 1500,
    description: 'Perfect for working professionals, University lecturers, or families alike. Strategically located right on the main GT Road Highway with seamless parking and quick transit to Jalandhar, LPU, or downtown Phagwara. Offers elegant balconies with highway view, security alarms, fire detectors, kitchen cabinets, and air-conditioning.',
    rating: 4.4,
    reviewsCount: 16,
    amenities: ['WiFi', 'Bed', 'AC', 'Parking', 'Kitchen', 'CCTV', 'Geyser', 'Power Backup', 'Refrigerator'],
    size: '950 sq.ft',
    genderPreference: 'Any',
    hostName: 'Harbhajan Singh',
    hostPhone: '+91 98312 00456',
    hostWhatsApp: '919831200456',
    hostAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=150&q=80',
    featured: false,
    addedDate: '2026-06-11'
  },
  {
    id: 'prop-11',
    title: '1 BHK Semi-Furnished Flat Near LPU Backside',
    price: 5500,
    type: '1 BHK',
    location: 'Law Gate, Near LPU',
    address: 'Ganesh Enclave, LPU Backside Road, Maheru, Phagwara, Punjab 144411',
    bedrooms: 1,
    bathrooms: 1,
    furnishing: 'Semi Furnished',
    ac: true,
    nearLPU: true,
    distanceToLPU: '400m (5 mins walk)',
    images: [
      'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=800&q=80'
    ],
    securityDeposit: 4000,
    brokerage: 0,
    description: 'Super independent 1 BHK flat for ultimate comfort and freedom. Features a dedicated kitchen setup where you can cook your own meals, clean bathroom, attached bedroom, study space, split AC installed. High-speed commercial WiFi is available for smooth study/remote work.',
    rating: 4.6,
    reviewsCount: 20,
    amenities: ['WiFi', 'Bed', 'AC', 'Kitchen', 'RO Water', 'Study Table', 'CCTV', 'Geyser', 'Power Backup'],
    size: '420 sq.ft',
    genderPreference: 'Any',
    hostName: 'Anil Kumar Chona',
    hostPhone: '+91 94171 23412',
    hostWhatsApp: '919417123412',
    hostAvatar: 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?auto=format&fit=crop&w=150&q=80',
    featured: false,
    addedDate: '2026-06-15'
  },
  {
    id: 'prop-12',
    title: 'Elite Independent House with Grand Lawn (5 BHK)',
    price: 32000,
    type: '5 BHK',
    location: 'Urban Estate, Phagwara',
    address: 'Villa 14, Phase-1 Gated Society, Urban Estate, Phagwara, Punjab 144401',
    bedrooms: 5,
    bathrooms: 5,
    furnishing: 'Furnished',
    ac: true,
    nearLPU: false,
    distanceToLPU: '6.4 km',
    images: [
      'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1536376072261-38c75010e6c9?auto=format&fit=crop&w=800&q=80'
    ],
    securityDeposit: 50000,
    brokerage: 10000,
    description: 'A spectacular ultra-exclusive 5 BHK super villa suited for elite joint families, NRIs or top-tier executives. Features high ceilings, personal office library, massive modern kitchen setup, five luxurious ensuite bedrooms, top-of-the-line VRF air conditioning systems, lush private yard space, complete solar backup power, and multi-car locked garage space.',
    rating: 5.0,
    reviewsCount: 6,
    amenities: ['WiFi', 'Bed', 'AC', 'Parking', 'Kitchen', 'Washing Machine', 'RO Water', 'Study Table', 'CCTV', 'Geyser', 'Power Backup', 'Refrigerator'],
    size: '4200 sq.ft',
    genderPreference: 'Family',
    hostName: 'Sardar Jagjit Singh Bajwa',
    hostPhone: '+91 98111 22335',
    hostWhatsApp: '919811122335',
    hostAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80',
    featured: true,
    addedDate: '2026-06-16'
  },
  {
    id: 'prop-13',
    title: 'Cozy Budget Room near Miya Ji Chowk',
    price: 3000,
    type: 'Single Room',
    location: 'Miya Ji Chowk, Phagwara',
    address: 'Near Old Post Office, Miya Ji Chowk Bazaar, Phagwara, Punjab 144401',
    bedrooms: 1,
    bathrooms: 1,
    furnishing: 'Unfurnished',
    ac: false,
    nearLPU: false,
    distanceToLPU: '5.2 km',
    images: [
      'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=800&q=80'
    ],
    securityDeposit: 1500,
    brokerage: 0,
    description: 'Budget independent room ideal for single men or hardworking professionals. Very simple, neat, and freshly whitewashed. Shared bathroom, 24-hour sweet corporation water, and direct owner interaction. Located close to city transport links and central retail lanes.',
    rating: 4.1,
    reviewsCount: 8,
    amenities: ['Parking', 'RO Water'],
    size: '100 sq.ft',
    genderPreference: 'Boys',
    hostName: 'Pandit Somnath',
    hostPhone: '+91 98012 34509',
    hostWhatsApp: '919801234509',
    hostAvatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=150&q=80',
    featured: false,
    addedDate: '2026-06-12'
  },
  {
    id: 'prop-14',
    title: 'Modern Student PG near Maheru G.T. Road (Co-ed Wings)',
    price: 5200,
    type: 'PG',
    location: 'Maheru, Near LPU',
    address: 'University Road Sector, Maheru village near G.T Road flyover, Phagwara, Punjab 144411',
    bedrooms: 1,
    bathrooms: 1,
    furnishing: 'Furnished',
    ac: true,
    nearLPU: true,
    distanceToLPU: '800m (10 mins walk)',
    images: [
      'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?auto=format&fit=crop&w=800&q=80'
    ],
    securityDeposit: 3500,
    brokerage: 0,
    description: 'High-class co-educational PG complex with strictly separated boys and girls residential blocks and common recreational space (Table tennis, gym, and lawn). Offers standard high-quality triple vegetarian catering, ultra high-speed fiber internet, washing facilities, power backup, study desks, and modern bathroom units.',
    rating: 4.7,
    reviewsCount: 31,
    amenities: ['WiFi', 'Bed', 'AC', 'Kitchen', 'Washing Machine', 'RO Water', 'Study Table', 'CCTV', 'Geyser', 'Power Backup', 'Meals Included', 'Refrigerator'],
    size: '160 sq.ft',
    genderPreference: 'Any',
    hostName: 'Ranjeet Singh Bhatia',
    hostPhone: '+91 97890 12345',
    hostWhatsApp: '919789012345',
    hostAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
    featured: false,
    addedDate: '2026-06-13'
  },
  {
    id: 'prop-15',
    title: 'Spacious 2 BHK Semi-Furnished Flat Near LPU',
    price: 8500,
    type: '2 BHK',
    location: 'Law Gate, Near LPU',
    address: 'Lane 5, Master Colony, Law Gate Backside, Maheru, Phagwara, Punjab 144411',
    bedrooms: 2,
    bathrooms: 2,
    furnishing: 'Semi Furnished',
    ac: false,
    nearLPU: true,
    distanceToLPU: '500m (6 mins walk)',
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=800&q=80'
    ],
    securityDeposit: 8000,
    brokerage: 0,
    description: 'Perfect, extra spacious layout consisting of two airy bedrooms, spacious closets, two Western washrooms, cozy living room kitchen setup, independent balconies. Gated building layout with biometric main entry locks. Highly recommended for friend groups of 2-4 LPU students.',
    rating: 4.5,
    reviewsCount: 14,
    amenities: ['WiFi', 'Bed', 'Parking', 'Kitchen', 'RO Water', 'Study Table', 'CCTV', 'Geyser', 'Power Backup', 'Refrigerator'],
    size: '850 sq.ft',
    genderPreference: 'Any',
    hostName: 'Sardar Sukhdev Singh',
    hostPhone: '+91 98456 78901',
    hostWhatsApp: '919845678901',
    hostAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=150&q=80',
    featured: false,
    addedDate: '2026-06-14'
  },
  {
    id: 'prop-16',
    title: 'Premium Independent 1 BHK with Big Balcony',
    price: 6800,
    type: '1 BHK',
    location: 'Maheru, Near LPU',
    address: 'Heights Residency, University Main Avenue, Maheru, Phagwara, Punjab 144411',
    bedrooms: 1,
    bathrooms: 1,
    furnishing: 'Furnished',
    ac: true,
    nearLPU: true,
    distanceToLPU: '300m (3 mins walk)',
    images: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1554995207-c18c203602cb?auto=format&fit=crop&w=800&q=80'
    ],
    securityDeposit: 6000,
    brokerage: 0,
    description: 'Splendid independent luxury 1 BHK studio flat with a breathtaking view of green farmlands from the grand running balcony. Includes cozy sofa unit, split AC, smart LED television, fully functional private kitchenette with dynamic double burner gas burner, RO installation, study console, and premium bedding.',
    rating: 4.8,
    reviewsCount: 23,
    amenities: ['WiFi', 'Bed', 'AC', 'Parking', 'Kitchen', 'RO Water', 'Study Table', 'CCTV', 'Geyser', 'Power Backup', 'Refrigerator'],
    size: '500 sq.ft',
    genderPreference: 'Any',
    hostName: 'Prof. Amrit Pal Singh',
    hostPhone: '+91 98144 55667',
    hostWhatsApp: '919814455667',
    hostAvatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=150&q=80',
    featured: true,
    addedDate: '2026-06-16'
  },
  {
    id: 'prop-17',
    title: 'Luxurious 3 BHK House flat in Gated Colony',
    price: 13500,
    type: '3 BHK',
    location: 'Hargobind Nagar, Phagwara',
    address: 'Shivalik Avenue, Hargobind Nagar Main Extension, Phagwara, Punjab 144401',
    bedrooms: 3,
    bathrooms: 3,
    furnishing: 'Semi Furnished',
    ac: true,
    nearLPU: false,
    distanceToLPU: '5.9 km',
    images: [
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=800&q=80'
    ],
    securityDeposit: 13500,
    brokerage: 2000,
    description: 'Immaculate semi-furnished 3 BHK flat situated inside a top-rated gated family community. Features 24-hour guarded gate locks, premium wooden texture tiles, fully modern modular cabinets kitchen, massive lounge, false-ceiling warm spotlights, and high luxury security networks. Best suited for decent corporate families.',
    rating: 4.7,
    reviewsCount: 12,
    amenities: ['WiFi', 'Bed', 'AC', 'Parking', 'Kitchen', 'RO Water', 'CCTV', 'Geyser', 'Power Backup'],
    size: '1450 sq.ft',
    genderPreference: 'Family',
    hostName: 'Dr. Devinder Dutta',
    hostPhone: '+91 98155 44332',
    hostWhatsApp: '919815544332',
    hostAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=150&q=80',
    featured: false,
    addedDate: '2026-06-03'
  },
  {
    id: 'prop-18',
    title: 'Budget Single Room with Bed & Cabinet (Boys)',
    price: 3500,
    type: 'Single Room',
    location: 'Law Gate, Near LPU',
    address: 'Hari Singh Colony, near Law Gate Flyover, Phagwara, Punjab 144411',
    bedrooms: 1,
    bathrooms: 1,
    furnishing: 'Furnished',
    ac: false,
    nearLPU: true,
    distanceToLPU: '280m (3 mins walk)',
    images: [
      'https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=800&q=80'
    ],
    securityDeposit: 2000,
    brokerage: 0,
    description: 'Very affordable single room with standard solid-wood bed, study table and wardrobe cabinet. Shared clean washroom with only one other room tenant. Unlimited High speed internet included for uninterrupted studies. Cool water filter and clean environment.',
    rating: 4.3,
    reviewsCount: 14,
    amenities: ['WiFi', 'Bed', 'RO Water', 'Study Table', 'CCTV', 'Power Backup'],
    size: '110 sq.ft',
    genderPreference: 'Boys',
    hostName: 'Sanjay Aggarwal',
    hostPhone: '+91 94119 12389',
    hostWhatsApp: '919411912389',
    hostAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80',
    featured: false,
    addedDate: '2026-06-18'
  },
  {
    id: 'prop-19',
    title: 'Independent 2 BHK Family Ground Floor House',
    price: 10000,
    type: 'Independent House',
    location: 'Plahi Road, Phagwara',
    address: 'Lane 4, Subhash Nagar, near Plahi Gate, Phagwara, Punjab 144401',
    bedrooms: 2,
    bathrooms: 2,
    furnishing: 'Semi Furnished',
    ac: false,
    nearLPU: false,
    distanceToLPU: '6.9 km',
    images: [
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=800&q=80'
    ],
    securityDeposit: 10000,
    brokerage: 0,
    description: 'Comfortable independent ground floor 2 BHK residence with dedicated small front lobby, marble flooring, two large rooms, standard wooden closets, direct independent water pump, separate electricity meter, and secure car/bike parking area inside. Extremely polite neighborhood.',
    rating: 4.5,
    reviewsCount: 7,
    amenities: ['Parking', 'Kitchen', 'RO Water', 'CCTV', 'Geyser'],
    size: '1200 sq.ft',
    genderPreference: 'Family',
    hostName: 'Madam Satwant Kaur',
    hostPhone: '+91 94789 22356',
    hostWhatsApp: '919478922356',
    hostAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=150&q=80',
    featured: false,
    addedDate: '2026-06-02'
  },
  {
    id: 'prop-20',
    title: 'Brand New Luxury 3 BHK Independent House',
    price: 18000,
    type: 'Independent House',
    location: 'Urban Estate, Phagwara',
    address: 'House 565, Sector-A, Urban Estate near Plahi Road, Phagwara, Punjab 144401',
    bedrooms: 3,
    bathrooms: 3,
    furnishing: 'Furnished',
    ac: true,
    nearLPU: false,
    distanceToLPU: '6.3 km',
    images: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=800&q=80'
    ],
    securityDeposit: 18000,
    brokerage: 2500,
    description: 'Stunning premium independent double-story building (3 BHK). Designed as per modern Vastu rules. Comes with two gorgeous sit-out balconies, private high security perimeter walls, automatic water sensors, modular premium kitchen setup, fully leather sofa units. Near top-tier Phagwara schools and medical care.',
    rating: 4.8,
    reviewsCount: 5,
    amenities: ['WiFi', 'Bed', 'AC', 'Parking', 'Kitchen', 'Washing Machine', 'RO Water', 'CCTV', 'Geyser', 'Power Backup', 'Refrigerator'],
    size: '2100 sq.ft',
    genderPreference: 'Family',
    hostName: 'Er. Sandeep Pathak',
    hostPhone: '+91 98555 12390',
    hostWhatsApp: '919855512390',
    hostAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
    featured: true,
    addedDate: '2026-06-19'
  }
];

export const TESTIMONIALS_DATA = [
  {
    id: 't-1',
    name: 'Amanpreet Dev',
    role: 'LPU B.Tech CSE Student',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=100&q=80',
    rating: 5,
    text: 'Being from Hyderabad, finding a trustable PG near Lovely Professional University was a big headache. "PG in Phagwara" helped me browse and filter realistic listings with direct verified owner details. Saved me massive brokerage fees!'
  },
  {
    id: 't-2',
    name: 'Dr. Priya Aggarwal',
    role: 'Assistant Professor, LPU',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=100&q=80',
    rating: 5,
    text: 'I wanted a high-quality 2 BHK apartment in Hargobind Nagar or Plahi road with good ventilation and parking. This platform had absolute real photographs and accurate security deposits. Extremely professional rent portal.'
  },
  {
    id: 't-3',
    name: 'Kshitiz Sethi',
    role: 'M.B.A Student from Delhi',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=100&q=80',
    rating: 5,
    text: 'Moving to Phagwara was smooth because of this service. Direct owner contacts, zero brokerage, double-verified student PG models near Law Gate. The single room I booked via WhatsApp matches 100% with the pics.'
  },
  {
    id: 't-4',
    name: 'Meenakshi & Family',
    role: 'Resident House Owners',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=100&q=80',
    rating: 4.8,
    text: 'We listed our independent ground floor estate on this platform and started receiving genuine polite queries within 2 days! Highly recommended for both listing owners and tenants seeking decent rent systems.'
  }
];

export const CATEGORIES_DATA = [
  {
    id: 'cat-pg',
    title: 'PG Accommodation',
    slug: 'PG' as PropertyType,
    count: 4,
    description: 'Complete student host rooms with quality organic meals, high privacy, and standard security locks.',
    icon: 'HomeIcon',
    image: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 'cat-1bhk',
    title: '1 BHK Studio Apartments',
    slug: '1 BHK' as PropertyType,
    count: 3,
    description: 'Neat personal studio rooms with independent modular kitchens, closets, and study balconies.',
    icon: 'BedDouble',
    image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 'cat-2bhk',
    title: '2 BHK Apartments & Flats',
    slug: '2 BHK' as PropertyType,
    count: 3,
    description: 'Spacious dual-sharing flats or homes for smart friend cohorts, couples, and premium families.',
    icon: 'Building2',
    image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 'cat-3bhk',
    title: '3 BHK Family Homes',
    slug: '3 BHK' as PropertyType,
    count: 3,
    description: 'Large luxury flats with triple ensuite master restrooms, high ventilation and gate guards.',
    icon: 'LayoutGrid',
    image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 'cat-house',
    title: 'Independent House / Villas',
    slug: 'Independent House' as PropertyType,
    count: 3,
    description: 'Magnificent luxury properties with private backyards, double story terraces and multi-car parking.',
    icon: 'Warehouse',
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=600&q=80'
  }
];

export const STATISTICS_DATA = [
  { value: '250+', label: 'Total Verified Listings' },
  { value: '1,800+', label: 'Happy Tenants Assisted' },
  { value: '12+', label: 'Prime Areas Covered' },
  { value: '100%', label: 'Direct Verified Hosts' }
];

export const ADVANTAGES_DATA = [
  {
    title: '100% Verified Listings',
    description: 'Every room picture, location scale, and monthly rental figure is double-verified on-ground by our agents in Phagwara.',
    icon: 'ShieldCheck'
  },
  {
    title: 'Most Affordable Rent models',
    description: 'No hidden student markups, inflated prices or surprise monthly service fees. Direct owner negotiation gives you true value.',
    icon: 'CirclePercent'
  },
  {
    title: 'Walking Distance to LPU',
    description: 'Over 60% of our premium catalog sits right near LPU Law Gate or Maheru village, minimizing daily travel cost & fatigue.',
    icon: 'Milestone'
  },
  {
    title: 'Direct Owner Connection',
    description: 'Connect direct to Sardar and families with zero to extremely minimal brokerage. Clear transparency from day 1.',
    icon: 'UserCheck'
  }
];
